joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

joint_neck_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_neck
    pid: {p: 0.01, i: 0.0, d: 0.05}

